[build]
beforeBuildCommand = "cd .. && trunk build --release"
beforeDevCommand = "cd .. && trunk serve --features logging"
devPath = "http://localhost:8080"
distDir = "../web-ui/dist"
withGlobalTauri = true

[package]
productName = "exponential-buckets-explorer"

[tauri.allowlist]
all = false

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "com.ddtkey.exponential-buckets-explorer"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

[tauri.bundle.deb]
depends = [ ]

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = [ ]

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
fullscreen = false
height = 600
resizable = true
title = "Exponential Buckets Explorer"
label = "exponential-buckets-explorer"
width = 800
