name: 'Release Desktop'

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: macos-latest
            target: x86_64-apple-darwin
            bundles: app,dmg
          - platform: macos-latest
            target: aarch64-apple-darwin
            bundles: app,dmg
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bundles: deb
          - platform: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bundles: deb
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi

    name: Desktop - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'wasm32-unknown-unknown,${{ matrix.settings.target }}'

      - name: install dependencies (ubuntu only)
        if: startsWith(matrix.settings.platform, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: cargo-bins/cargo-binstall@main
      - name: Download and install Trunk binary
        run: cargo binstall --no-confirm trunk

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.settings.target }} --bundles ${{ matrix.settings.bundles }}
